In [ ]:
# 1) shape and reshape
import numpy as np
n = list(map(int,input().split()))
a = np.array(n)
b = a.reshape(3,3)
print(b)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 2) Arrays
import numpy
def arrays(arr):
    a = numpy.array(arr,float)
    b = numpy.flip(a)
    return b

arr = input().strip().split(' ')
result = arrays(arr)
print(result)


1 2 3 4 5
[5. 4. 3. 2. 1.]


In [ ]:
# 3) Concatenate

import numpy as np
c=[]
d=[]
n,m,p = list(map(int,input().split()))
#print(n,m,p)

for i in range(n):
    id = list(map(int,input().split()))
    c.append(id)
#print(c)
for i in range(m):
    id1 = list(map(int,input().split()))
    d.append(id1)
#print(d)
a = np.concatenate([c,d], axis = 0)
print(a)

2 3 2
4 5
6 5
7 8
 11 22
1 2
[[ 4  5]
 [ 6  5]
 [ 7  8]
 [11 22]
 [ 1  2]]


In [ ]:
# 4) sum and prod

import numpy as np
arr = []
n,m = list(map(int,input().split()))

for i in range(n):
    id = list(map(int,input().split()))
    arr.append(id)

sum = np.sum(arr,axis=0)
#print(sum)
prd = np.prod(sum)
print(prd)


2 2
1 2 
4 5
35


In [ ]:
# 5) min and max

import numpy as np

n,m = list(map(int,input().split()))
c = []
for i in range(n):
    id = list(map(int,input().split()))
    c.append(id)

mini = np.min(c,axis = 1)
maxi = np.max(mini)
print(maxi)

4 2
5 9
7 3
1 2
7 6
6


In [ ]:
# 6) zeros and ones

import numpy as np
n = list(map(int,input().split()))

a = np.zeros((n),int)
print(a)
    
b = np.ones((n),int)
print(b)
    

1 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
# 7) Mean,var and std

import numpy as np

n,m = list(map(int,input().split()))
c = []
for i in range(n):
    id = list(map(int,input().split()))
    c.append(id)

mean = np.mean(c, axis = 1)
var = np.var(c, axis = 0)
std = np.std(c, axis = None)

arnd = np.around(std,11)  

print(mean)
print(var)
print(arnd)


2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [ ]:
# 8) Eye and Identity

import numpy as np
np.set_printoptions(legacy='1.13')

n,m = list(map(int,input().split()))
a = np.eye(n,m)
print(a)


3 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


In [1]:
# 9) Transpose and Flatten

import numpy as np
c = []
n,m = list(map(int,input().split()))
for i in range(n):
    arr = list(map(int,input().split()))
    c.append(arr)

array = np.array(c)
trans = np.transpose(array)
flatt = array.flatten()
print(trans)
print(flatt)


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [2]:
# 10) Floo,Ceil and rint

import numpy as np
np.set_printoptions(legacy='1.13')

data = list(map(float,input().split()))

array = np.array(data)
floor = np.floor(array)
ceil = np.ceil(array)
rint = np.rint(array)

print(floor)
print(ceil)
print(rint)

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [3]:
# 11) Array Mathematics

import numpy as np
a = []
b = []
n,m = list(map(int,input().split()))
for i in range(n):
    data = list(map(int,input().split()))
    a.append(data)
for i in range(n):
    data1 = list(map(int,input().split()))
    b.append(data1)
    

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.floor_divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [12]:
# 12)  Linear Algebra

import numpy as np
c = []
n = int(input())
for i in range(n):
    data = list(map(float,input().split()))
    c.append(data)
    

a = np.linalg.det(c)
arnd = np.around(a,2)
print(arnd)

3
1 2 3
4 5 6
1 2 1
6.0


In [13]:
# 13) Dot and Cross

import numpy as np

n = int(input())
a=[]
b=[]
for i in range(n):
    arr = list(map(int,input().split()))
    a.append(arr)
for i in range(n):
    arr1 = list(map(int,input().split()))
    b.append(arr1)
    
c = np.dot(a,b)
print(c)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [14]:
# 14) Inner and Outer

import numpy as np

a = list(map(int,input().split()))
b = list(map(int,input().split()))
inn = np.inner(a,b)
out = np.outer(a,b)

print(inn)
print(out)



0 1
2 3
3
[[0 0]
 [2 3]]


In [15]:
# 15) Polynomials

import numpy as np

a = list(map(float,input().split()))
b = int(input())

c = np.polyval(a,b)
print(c)


1.1 2 3
0
3.0
